<a href="https://colab.research.google.com/github/Great-erf/pythone-code/blob/pythone/cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Section

In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import math

In [2]:
data =pd.read_csv("CancerData.csv1111111111111 (2).csv")

In [3]:
df = pd.DataFrame(data )
df

MARIS VARINC COVRINS  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  \
0                0.323939    0.013122   -0.780502    0.008651   -0.496051   
1                0.393427   -0.247381   -0.074042    0.265081    0.266291   
2                0.387192   -0.189083   -0.132774    0.141924    0.299997   
3                0.317045    0.145056    0.531521    0.353259   -0.597657   
4                0.264262   -0.244319    0.097636    0.268574    0.338090   
..                    ...         ...         ...         ...         ...   
486                   NaN         NaN         NaN         NaN         NaN   
487                   NaN         NaN         NaN         NaN         NaN   
488                   NaN         NaN         NaN         NaN         NaN   
489                   NaN         NaN         NaN         NaN         NaN   
490                   NaN         NaN         NaN         NaN         NaN   

     Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  \
0      0.010927   -0.102155   -0.170292    0.003580         NaN  ...   
1     -0.211751    0.220704    0.175544    0.716235         NaN  ...   
2     -0.214178    0.352571    0.224258   -0.682708         NaN  ...   
3     -0.270267    0.119324   -0.153077   -0.056796         NaN  ...   
4      0.192752   -0.415841   -0.674976   -0.093993         NaN  ...   
..          ...         ...         ...         ...         ...  ...   
486         NaN         NaN         NaN         NaN         NaN  ...   
487         NaN         NaN         NaN         NaN         NaN  ...   
488         NaN         NaN         NaN         NaN         NaN  ...   
489         NaN         NaN         NaN         NaN         NaN  ...   
490         NaN         NaN         NaN         NaN         NaN  ...   

     EHTML DROSTI PISHBINI BA ASAS  CLUSTERING  Unnamed: 34  \
0                                    PFITS-1-1          NaN   
1                                  0.078175896          NaN   
2                                   0.93442623          NaN   
3                                  0.078175896          NaN   
4                                   0.93442623          NaN   
..                                         ...          ...   
486                                0.078175896          NaN   
487                                0.078175896          NaN   
488                                 0.93442623          NaN   
489                                 0.93442623          NaN   
490                                0.078175896          NaN   

     EHTML DROSTI PISHBINI BA ASAS  DADE HAYE ASLI  Unnamed: 36  \
0                                        PFITS_2-1          NaN   
1                                      0.424443635          NaN   
2                                      0.424443635          NaN   
3                                      0.109692686          NaN   
4                                      0.643389255          NaN   
..                                             ...          ...   
486                                     0.02016946          NaN   
487                                    0.109692686          NaN   
488                                    0.984764243          NaN   
489                                    0.109692686          NaN   
490                                    0.643389255          NaN   

     clustring -30%test  Unnamed: 38  \
0                   1.0          NaN   
1                   1.0          NaN   
2                   1.0          NaN   
3                   1.0          NaN   
4                   1.0          NaN   
..                  ...          ...   
486                 NaN          NaN   
487                 NaN          NaN   
488                 NaN          NaN   
489                 NaN          NaN   
490                 NaN          NaN   

     EHTML DROSTI PISHBINI BA ASAS  DADE HAYE ASLI BRYE 30%HA  Unnamed: 40  \
0                                            PFITS-2-2                 NaN   
1               

In [5]:
data2 =pd.read_csv("CancerData.csv")
df2 = pd.DataFrame(data2)
df2




Clump Thickness  Uniformity of Cell Size   Uniformity of Cell Shape  \
0                  5                         1                         1   
1                  5                         4                         4   
2                  3                         1                         1   
3                  6                         8                         8   
4                  4                         1                         1   
..               ...                       ...                       ...   
694                3                         1                         1   
695                2                         1                         1   
696                5                        10                        10   
697                4                         8                         6   
698                4                         8                         8   

     Marginal Adhesion  Single Epithelial Cell Size Bare Nuclei    \
0                    1                            2             1   
1                    5                            7            10   
2                    1                            2             2   
3                    1                            3             4   
4                    3                            2             1   
..                 ...                          ...           ...   
694                  1                            3             2   
695                  1                            2             1   
696                  3                            7             3   
697                  4                            3             4   
698                  5                            4             5   

     Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0                  3                1        1      2  
1                  3                2        1      2  
2                  3                1        1      2  
3                  3                7        1      2  
4                  3                1        1      2  
..               ...              ...      ...    ...  
694                1                1        1      2  
695                1                1        1      2  
696                8               10        2      4  
697               10                6        1      4  
698               10                4        1      4  

[699 rows x 10 columns]

In [6]:
df.columns

Index(['MARIS VARINC COVRINS', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9', 'MOALEFE HAYE ASLI ESTKHRAJ SHODE (PCA)', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'MATRIS corlations', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'clustering',
       'Unnamed: 32', 'EHTML DROSTI PISHBINI BA ASAS  CLUSTERING',
       'Unnamed: 34', 'EHTML DROSTI PISHBINI BA ASAS  DADE HAYE ASLI',
       'Unnamed: 36', 'clustring -30%test', 'Unnamed: 38',
       'EHTML DROSTI PISHBINI BA ASAS  DADE HAYE ASLI BRYE 30%HA',
       'Unnamed: 40', 'Unnamed: 41',
       'EHTML DROSTI PISHBINI BA ASAS  DADE HAYE ASLI BRYE 30%HA.1'],
      dtype='object')

In [7]:
(df['EHTML DROSTI PISHBINI BA ASAS  DADE HAYE ASLI'])

0        PFITS_2-1
1      0.424443635
2      0.424443635
3      0.109692686
4      0.643389255
          ...     
486     0.02016946
487    0.109692686
488    0.984764243
489    0.109692686
490    0.643389255
Name: EHTML DROSTI PISHBINI BA ASAS  DADE HAYE ASLI, Length: 491, dtype: object

In [8]:
df3=pd.DataFrame(df['EHTML DROSTI PISHBINI BA ASAS  DADE HAYE ASLI'],index=range(1,len(df['EHTML DROSTI PISHBINI BA ASAS  DADE HAYE ASLI'])))
df3

EHTML DROSTI PISHBINI BA ASAS  DADE HAYE ASLI
1                                     0.424443635
2                                     0.424443635
3                                     0.109692686
4                                     0.643389255
5                                      0.23161383
..                                            ...
486                                    0.02016946
487                                   0.109692686
488                                   0.984764243
489                                   0.109692686
490                                   0.643389255

[490 rows x 1 columns]

In [12]:
df3['EHTML DROSTI PISHBINI BA ASAS  DADE HAYE ASLI'] = df3['EHTML DROSTI PISHBINI BA ASAS  DADE HAYE ASLI'].astype(float)

In [13]:
df3.dtypes

EHTML DROSTI PISHBINI BA ASAS  DADE HAYE ASLI    float64
dtype: object

In [16]:
#dade haye mored niyaz ma: Yi ha
df3

EHTML DROSTI PISHBINI BA ASAS  DADE HAYE ASLI
1                                         0.424444
2                                         0.424444
3                                         0.109693
4                                         0.643389
5                                         0.231614
..                                             ...
486                                       0.020169
487                                       0.109693
488                                       0.984764
489                                       0.109693
490                                       0.643389

[490 rows x 1 columns]

In [17]:
df2.columns

Index(['Clump Thickness', 'Uniformity of Cell Size ',
       'Uniformity of Cell Shape', 'Marginal Adhesion',
       'Single Epithelial Cell Size', 'Bare Nuclei  ', 'Bland Chromatin',
       'Normal Nucleoli', 'Mitoses', 'Class'],
      dtype='object')

In [25]:
df4 =pd.DataFrame(df2['Class'],index=range(209,len(df2['Class'])))
df4

Class
209      2
210      4
211      4
212      2
213      4
..     ...
694      2
695      2
696      4
697      4
698      4

[490 rows x 1 columns]

In [28]:
df4.dtypes

Class    int64
dtype: object

In [34]:
df4['Class'] = df4['Class'].astype(float)

In [35]:
df4.dtypes

Class    float64
dtype: object

In [36]:
df3.dtypes

EHTML DROSTI PISHBINI BA ASAS  DADE HAYE ASLI    float64
dtype: object

In [143]:
a=df4['Class'].to_numpy()
a

array([2., 4., 4., 2., 4., 4., 4., 2., 2., 4., 2., 2., 4., 4., 4., 4., 2.,
       4., 4., 2., 4., 4., 4., 2., 4., 2., 2., 4., 4., 4., 4., 2., 2., 2.,
       2., 2., 2., 4., 4., 2., 2., 2., 4., 2., 4., 4., 4., 2., 2., 2., 2.,
       4., 4., 4., 4., 4., 2., 4., 4., 4., 2., 4., 2., 4., 4., 2., 2., 2.,
       2., 2., 4., 2., 2., 4., 4., 4., 4., 4., 2., 4., 4., 2., 2., 4., 4.,
       2., 4., 2., 2., 2., 4., 4., 2., 4., 2., 4., 4., 2., 2., 4., 2., 2.,
       2., 4., 2., 2., 2., 4., 4., 2., 2., 4., 2., 2., 4., 2., 2., 4., 2.,
       4., 4., 4., 2., 2., 4., 4., 2., 4., 2., 2., 4., 4., 2., 2., 2., 4.,
       2., 2., 2., 4., 4., 2., 2., 2., 4., 2., 2., 4., 4., 4., 4., 4., 4.,
       2., 2., 2., 2., 4., 4., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 4., 2., 2., 2., 2., 4., 2., 2., 2., 2., 4., 2., 2., 2., 2.,
       2., 2., 2., 2., 4., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 4.,
       2., 4., 2., 4., 2., 2., 2., 2., 4., 2., 2., 2., 4., 2., 4., 2., 2.,
       2., 2., 2., 2., 2.

In [144]:
b= df3['EHTML DROSTI PISHBINI BA ASAS  DADE HAYE ASLI'].to_numpy()
b

array([0.42444363, 0.42444363, 0.10969269, 0.64338925, 0.23161383,
       0.91524532, 0.02016946, 0.04794597, 0.04794597, 0.23161383,
       0.02016946, 0.04794597, 0.42444363, 0.02016946, 0.91524532,
       0.81529169, 0.23161383, 0.23161383, 0.98476424, 0.64338925,
       0.81529169, 0.98476424, 0.10969269, 0.91524532, 0.02016946,
       0.42444363, 0.10969269, 0.42444363, 0.04794597, 0.02016946,
       0.10969269, 0.04794597, 0.98476424, 0.04794597, 0.10969269,
       0.04794597, 0.98476424, 0.64338925, 0.42444363, 0.04794597,
       0.64338925, 0.98476424, 0.64338925, 0.42444363, 0.98476424,
       0.02016946, 0.10969269, 0.02016946, 0.23161383, 0.81529169,
       0.96352932, 0.42444363, 0.98476424, 0.42444363, 0.98476424,
       0.98476424, 0.91524532, 0.91524532, 0.42444363, 0.96352932,
       0.42444363, 0.02016946, 0.96352932, 0.64338925, 0.02016946,
       0.98476424, 0.23161383, 0.42444363, 0.91524532, 0.02016946,
       0.42444363, 0.64338925, 0.02016946, 0.96352932, 0.98476

In [157]:
sum = 0;
for i in range(1,490):
  sum = sum + (a[i]-b[i])
print(sum)
print(np.size(sum))

1089.4244436789998
1


In [158]:
sum2 = sum**2

In [160]:
final_result = math.sqrt(sum2)/490
final_result

2.2233151911816322

قسمت بعد

In [125]:

df6=pd.DataFrame(df['EHTML DROSTI PISHBINI BA ASAS  CLUSTERING'],index=range(1,len(df['EHTML DROSTI PISHBINI BA ASAS  CLUSTERING'])))
df6

EHTML DROSTI PISHBINI BA ASAS  CLUSTERING
1                                 0.078175896
2                                  0.93442623
3                                 0.078175896
4                                  0.93442623
5                                 0.078175896
..                                        ...
486                               0.078175896
487                               0.078175896
488                                0.93442623
489                                0.93442623
490                               0.078175896

[490 rows x 1 columns]

In [126]:
df6['EHTML DROSTI PISHBINI BA ASAS  CLUSTERING'] = df6['EHTML DROSTI PISHBINI BA ASAS  CLUSTERING'].astype(float)

In [161]:
c=df6['EHTML DROSTI PISHBINI BA ASAS  CLUSTERING'].to_numpy()
c

array([0.0781759 , 0.93442623, 0.0781759 , 0.93442623, 0.0781759 ,
       0.93442623, 0.0781759 , 0.0781759 , 0.0781759 , 0.0781759 ,
       0.0781759 , 0.0781759 , 0.0781759 , 0.0781759 , 0.93442623,
       0.93442623, 0.0781759 , 0.0781759 , 0.93442623, 0.0781759 ,
       0.93442623, 0.93442623, 0.0781759 , 0.93442623, 0.0781759 ,
       0.0781759 , 0.0781759 , 0.0781759 , 0.0781759 , 0.0781759 ,
       0.0781759 , 0.0781759 , 0.93442623, 0.0781759 , 0.0781759 ,
       0.0781759 , 0.93442623, 0.0781759 , 0.93442623, 0.93442623,
       0.93442623, 0.93442623, 0.93442623, 0.0781759 , 0.93442623,
       0.0781759 , 0.93442623, 0.0781759 , 0.0781759 , 0.93442623,
       0.0781759 , 0.0781759 , 0.93442623, 0.93442623, 0.93442623,
       0.0781759 , 0.93442623, 0.93442623, 0.93442623, 0.93442623,
       0.93442623, 0.0781759 , 0.93442623, 0.93442623, 0.0781759 ,
       0.0781759 , 0.0781759 , 0.93442623, 0.93442623, 0.0781759 ,
       0.0781759 , 0.93442623, 0.0781759 , 0.93442623, 0.07817

In [162]:
data3 =pd.read_csv("CancerData.csv1111111111111.csv")

In [163]:
df7 = pd.DataFrame(data3 )
df7

?????? ??????? ?????????  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  \
0                    0.323939    0.013122   -0.780502    0.008651   -0.496051   
1                    0.393427   -0.247381   -0.074042    0.265081    0.266291   
2                    0.387192   -0.189083   -0.132774    0.141924    0.299997   
3                    0.317045    0.145056    0.531521    0.353259   -0.597657   
4                    0.264262   -0.244319    0.097636    0.268574    0.338090   
..                        ...         ...         ...         ...         ...   
486                       NaN         NaN         NaN         NaN         NaN   
487                       NaN         NaN         NaN         NaN         NaN   
488                       NaN         NaN         NaN         NaN         NaN   
489                       NaN         NaN         NaN         NaN         NaN   
490                       NaN         NaN         NaN         NaN         NaN   

     Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  \
0      0.010927   -0.102155   -0.170292    0.003580         NaN  ...   
1     -0.211751    0.220704    0.175544    0.716235         NaN  ...   
2     -0.214178    0.352571    0.224258   -0.682708         NaN  ...   
3     -0.270267    0.119324   -0.153077   -0.056796         NaN  ...   
4      0.192752   -0.415841   -0.674976   -0.093993         NaN  ...   
..          ...         ...         ...         ...         ...  ...   
486         NaN         NaN         NaN         NaN         NaN  ...   
487         NaN         NaN         NaN         NaN         NaN  ...   
488         NaN         NaN         NaN         NaN         NaN  ...   
489         NaN         NaN         NaN         NaN         NaN  ...   
490         NaN         NaN         NaN         NaN         NaN  ...   

     ?????? ????? ??????? ?? ???? CLUSTERING  Unnamed: 35  \
0                                  PFITS-1-1          NaN   
1                                0.078175896          NaN   
2                                 0.93442623          NaN   
3                                0.078175896          NaN   
4                                 0.93442623          NaN   
..                                       ...          ...   
486                              0.078175896          NaN   
487                              0.078175896          NaN   
488                               0.93442623          NaN   
489                               0.93442623          NaN   
490                              0.078175896          NaN   

     ?????? ????? ??????? ?? ???? ???? ??? ????   Unnamed: 37  \
0                                      PFITS_2-1          NaN   
1                                    0.424443635          NaN   
2                                    0.424443635          NaN   
3                                    0.109692686          NaN   
4                                    0.643389255          NaN   
..                                           ...          ...   
486                                   0.02016946          NaN   
487                                  0.109692686          NaN   
488                                  0.984764243          NaN   
489                                  0.109692686          NaN   
490                                  0.643389255          NaN   

     clustring -30%test  Unnamed: 39  \
0                   1.0          NaN   
1                   1.0          NaN   
2                   1.0          NaN   
3                   1.0          NaN   
4                   1.0          NaN   
..                  ...          ...   
486                 NaN          NaN   
487                 NaN          NaN   
488                 NaN          NaN   
489                 NaN          NaN   
490                 NaN          NaN   

     ?????? ????? ??????? ?? ???? ???? ??? ???? ???? 30%??  Unnamed: 41  \
0                                            PFITS-2-2              NaN   
1                     

In [164]:
df7.columns

Index(['?????? ??????? ?????????', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9', '????? ??? ???? ??????? ???(PCA)', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', '?????????',
       'Unnamed: 21', '?????? ??????? corlations', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'clustering', 'Unnamed: 33', '?????? ????? ??????? ?? ???? CLUSTERING',
       'Unnamed: 35', '?????? ????? ??????? ?? ???? ???? ??? ???? ',
       'Unnamed: 37', 'clustring -30%test', 'Unnamed: 39',
       '?????? ????? ??????? ?? ???? ???? ??? ???? ???? 30%??', 'Unnamed: 41',
       'Unnamed: 42', '?????? ????? ??????? ?? ???? CLUSTERING ???? 30%??'],
      dtype='object')

In [167]:
df8=pd.DataFrame(df7['clustering'],index=range(1,len(df['clustering'])))
df8

clustering
1           2.0
2           1.0
3           2.0
4           1.0
5           2.0
..          ...
486         1.0
487         2.0
488         2.0
489         1.0
490         NaN

[490 rows x 1 columns]

In [202]:
df8['clustering'] = df8['clustering'].astype(float)

In [203]:
d=df8['clustering'].to_numpy()
d

array([ 2.,  1.,  2.,  1.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        2.,  2.,  1.,  1.,  2.,  1.,  2.,  2.,  1.,  2.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,  1.,  2.,  1.,  2.,  2.,
        2.,  2.,  2.,  1.,  2.,  1.,  2.,  1.,  1.,  2.,  1.,  1.,  2.,
        2.,  2.,  1.,  2.,  2.,  2.,  2.,  2.,  1.,  2.,  2.,  1.,  1.,
        1.,  2.,  2.,  1.,  1.,  2.,  1.,  2.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  1.,  1.,  2.,  2.,
        1.,  2.,  2.,  1.,  2.,  1.,  2.,  2.,  2.,  1.,  1.,  1.,  2.,
        1.,  1.,  1.,  1.,  2.,  2.,  2.,  1.,  2.,  1.,  1.,  1.,  1.,
        1.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  2.,  1.,  2.,  2.,  1.,  2.,  2.,  1.,  1.,  2.,  1.,
        1.,  1.,  2.,  2.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  1.,  1.,
        1.,  1.,  1.,  2.,  2.,  2.,  1.,  2.,  1.,  2.,  1.,  1

In [204]:
np.size(d)==np.size(c)

True

In [205]:
sumdo = 0;
for i in range(1,490):
  sumdo = sumdo + (d[i]-c[i])
print(sumdo)
print(np.size(sumdo))

nan
1


In [206]:
sumdovom2=sumdovom**2
sumdovom2

nan

In [207]:
final_result = math.sqrt(sumdovom2)/490
final_result

nan

In [210]:
d-c

array([1.9218241 , 0.06557377, 1.9218241 , 0.06557377, 1.9218241 ,
       0.06557377, 0.9218241 , 0.9218241 , 0.9218241 , 0.9218241 ,
       0.9218241 , 0.9218241 , 0.9218241 , 1.9218241 , 1.06557377,
       0.06557377, 0.9218241 , 1.9218241 , 0.06557377, 1.9218241 ,
       1.06557377, 0.06557377, 1.9218241 , 0.06557377, 0.9218241 ,
       0.9218241 , 0.9218241 , 0.9218241 , 0.9218241 , 0.9218241 ,
       0.9218241 , 1.9218241 , 0.06557377, 0.9218241 , 0.9218241 ,
       1.9218241 , 0.06557377, 1.9218241 , 1.06557377, 1.06557377,
       1.06557377, 1.06557377, 0.06557377, 1.9218241 , 0.06557377,
       1.9218241 , 0.06557377, 0.9218241 , 1.9218241 , 0.06557377,
       0.9218241 , 1.9218241 , 1.06557377, 1.06557377, 0.06557377,
       1.9218241 , 1.06557377, 1.06557377, 1.06557377, 1.06557377,
       0.06557377, 1.9218241 , 1.06557377, 0.06557377, 0.9218241 ,
       0.9218241 , 1.9218241 , 1.06557377, 0.06557377, 0.9218241 ,
       1.9218241 , 0.06557377, 1.9218241 , 0.06557377, 0.92182

In [214]:
c.dtype

dtype('float64')